environment:
  maxX: 10.0
  maxY: 10.0

pathPlanner:
  bias: 0.1
  iteration: 10000
  stepSize: 0.2

Filter:
  M: 1000
  stepSize: 0.15
  resampleThreshold: 0.75
  gridSizeX: 50
  gridSizeY: 50
  maxPropogationAttempts: 20
  maxObservedScore: 10
  observedDecayRate: 0.995
  densityThreshold: 0.026
  densityThresholdReset: 0.026

agent:
  agentInitialX: 1.0
  agentInitialY: 1.0
  agentInitialHeading: 0.0

sensor:
  fovFractionOfPi: 3.0
  range: 2.0

misc:
  maxIterations: 2000
  outputFile: "output_gm.csv"