environment:
  maxX: 10.0
  maxY: 10.0

pathPlanner:
  bias: 0.1
  iteration: 10000
  stepSize: 0.2

particleFilter:
  Ns: 1000
  stepSize: 0.15
  resampleThreshold: 0.75
  gridSizeX: 50
  gridSizeY: 50
  maxPropogationAttempts: 20
  maxObservedScore: 10
  observedDecayRate: 0.995
  densityThreshold: 0.018
  densityThresholdReset: 0.016

vehicle:
  vehicleInitialX: 1.0
  vehicleInitialY: 1.0
  vehicleInitialHeading: 0.0

sensor:
  fovFractionOfPi: 3.0
  range: 2.0

misc:
  maxIterations: 2000
  outputFile: "log.csv"